# Generated by Django 5.1.5 on 2025-02-05 17:39

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=blog.models.get_file_path),
        ),
    ]
