# Generated by Django 5.1.5 on 2025-06-17 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_later_users',
            field=models.ManyToManyField(related_name='read_later_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
